def get_rules():
    return {
        "browsers": {
            "chrome.exe",
            "msedge.exe",
            "firefox.exe",
            "brave.exe",
            "whale.exe",
            "opera.exe",
            "vivaldi.exe",
        },
        "developers": {
            "eclipse.exe",
            "idea64.exe",
            "pycharm64.exe",
            "webstorm64.exe",
            "clion64.exe",
            "rider64.exe",
            "goland64.exe",
            "code.exe",
            "devenv.exe",
            "visualstudio.exe",
            "studio64.exe",
            "sublime_text.exe",
        },
        "documents": {
            "winword.exe",
            "powerpnt.exe",
            "excel.exe",
            "hwp.exe",
            "acrord32.exe",
            "acrord64.exe",
            "sumatrapdf.exe",
            "foxitreader.exe",
            "notepad++.exe",
        },
        "media_players": {
            "potplayermini64.exe",
            "vlc.exe",
            "kmplayer.exe",
            "gom.exe",
            "mpc-hc.exe",
            "mpc-hc64.exe",
            "mpc-be.exe",
        },
        "web_media_keywords": {
            "youtube",
            "netflix",
            "twitch",
            "chzzk",
            "disney+",
            "wavve",
            "tving",
            "afreecatv",
            "watcha",
            "primevideo",
            "prime video",
            "coupangplay",
            "coupang play",
            "laftel",
            "spotify",
            "soundcloud",
            "유튜브",
            "넷플릭스",
            "티빙",
            "웨이브",
            "쿠팡플레이",
        },
        "web_study_keywords": {
            "github",
            "gitlab",
            "stackoverflow",
            "stackexchange",
            "tistory",
            "velog",
            "notion",
            "mdn",
            "wikipedia",
            "w3schools",
            "geeksforgeeks",
            "baeldung",
            "arxiv",
            "docs",
            "documentation",
        },
        "title_extract_patterns": [
            r"^\[(?P<title>[^\]]+)\]\s*.*$",
            r"^(?P<title>.+?)\s*[|:]\s*.*$",
            r"^(?P<title>.+?)\s*-\s*(steam|epic|gog|origin|uplay|ubisoft|battlenet|battle\.net|xbox|launcher)\b.*$",
            r"^(?P<title>.+?)\s*-\s*.*$",
        ],
    }
